language: python
python:
  - "3.6"
install:
  - pip3 install codecov
  - pip3 install mkdocs
  - pip3 install -r requirements.txt
jobs:
  include:
  - stage: "Tests"
    name: "Unit Tests"
    script: nosetests -v --with-coverage tests/*
    after_success:
    - codecov
  - stage: "Deploy"
    name: "Deploy Github Pages"
    script: mkdocs gh-deploy
